# ------------------------------------------------------------------------- #
#                                 RHSignItem                                #
#                                 ==========                                #
#                    Thank you for using "RHSignItem"!~                     #
#         If you like my plugin, please consider giving it a star.          #
#     I'm always open to suggestions for improvements or new ideas! :)      #
# ------------------------------------------------------------------------- #
#  In this file, you can configure how the plugin should work.              #
#                                                                           #
#  The MiniMessage format is used for messages.                             #
#  Documentation: https://docs.advntr.dev/minimessage/format                #
#                                                                           #
#  Please remember to always use " or ' for long or nested strings.         #
#                                                                           #
#  In the signature section, you can use the following placeholders:        #
#     %text%    -   the text input, only in 'DEFAULT'                       #
#     %player%  -   the player's name                                       #
#     %date%    -   current date                                            #
#     %time%    -   current time                                            #
#                                                                           #
#  Alternatively, you can use all placeholders from PlaceholderAPI,         #
#  provided that the plugin and all required expansions are installed.      #
# ------------------------------------------------------------------------- #

settings:
  content:
    DEFAULT:
      - "<white>%text%"
      - ""
      - "<gray>Signed by <green><bold>%player%<reset><gray> on <yellow><bold>%date%<reset> <yellow><bold>%time%<reset>"
    SHORT:
      - "<gray>Signed by <green><bold>%player%<reset><gray> on <yellow><bold>%date%<reset> <yellow><bold>%time%<reset>"
  locale: "en_US"
  formats:
    date: "MM/dd/yyyy"
    time: "HH:mm:ss"
  max-stack-size: 1
  auto-lock:
    enabled: false
    permission-based: true
  item-blacklist:
    - STRUCTURE_VOID
    - LIGHT
    - JIGSAW
  deny-items-with-lore: false
  offhand-item-mode:
    enabled: false
    type: GLOW_INK_SAC
    use-on-action: true
  enable-sounds: true
  vault:
    enabled: false
    cost: 250.00
    actions:
      sign: true
      delete: true
      lock: true
      unlock: true
      rename: true
    messages:
      payment-successful: true
      payment-failed: true
